steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - inference/mosec/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/medical-cdss-mosec:${_IMAGE_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - inference/gateway/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/medical-cdss-gateway:${_IMAGE_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/medical-cdss-backend:${_IMAGE_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/medical-cdss-mosec:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/medical-cdss-gateway:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/medical-cdss-backend:${_IMAGE_TAG}

substitutions:
  _REGION: asia-southeast1
  _AR_REPOSITORY: bhsd-models
  _IMAGE_TAG: manual

options:
  logging: CLOUD_LOGGING_ONLY
