# Generated by Django 6.0.7 on 2026-07-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "보안 감사 이벤트",
                "verbose_name_plural": "보안 감사 이벤트",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "사용자 의료기관 프로필",
                "verbose_name_plural": "사용자 의료기관 프로필",
            },
        ),
    ]
