# Generated by Django 6.0.7 on 2026-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("ct_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ct_file", models.FileField(upload_to="ct_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
