# Generated by Django 6.0.7 on 2026-07-27 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="review_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="review_status",
            field=models.CharField(
                choices=[("pending", "검토 대기"), ("reviewed", "검토 완료")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cdss_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="subject_id",
            field=models.CharField(
                db_index=True, default="DEMO-UNASSIGNED", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_cdss_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
