# Generated by Django 6.0.7 on 2026-07-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_review_note_case_review_status_case_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={"verbose_name": "CT 검사", "verbose_name_plural": "CT 검사"},
        ),
    ]
